name = "DualSignals"
uuid = "e4247b8d-50b5-41ef-b53d-f6e21a6bdac0"
version = "0.1.2"
authors = ["Riccardo Boero <ribo@nilu.no>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
CSV = "0.10"
Dates = "1.9"
JSON3 = "1"
JuMP = "1"
MathOptInterface = "1"
Statistics = "1.10"
StructTypes = "1"
julia = "1.10"
