name = "DualSignals"
uuid = "e4247b8d-50b5-41ef-b53d-f6e21a6bdac0"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
Dates = "1.9"
JSON3 = "1"
StructTypes = "1"
julia = "1.12"

